// Translation API using Google Translate
import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(
  req: VercelRequest,
  res: VercelResponse,
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { texts, targetLang, sourceLang = 'en' } = req.body;

    if (!texts || !targetLang) {
      return res.status(400).json({ error: 'Missing required parameters' });
    }

    // For now, return a simple transformation
    // In production, you would integrate with Google Translate API or another translation service
    // You would need to add GOOGLE_TRANSLATE_API_KEY to your environment variables

    // Mock translation for demonstration
    // In production, replace with Google Translate API
    const translations = texts.map((text: string) => {
      // Check if it's a number or special character only
      if (/^[\d\s\W]+$/.test(text)) {
        return text; // Don't translate numbers and special chars
      }

      // Basic mock translations
      const basicTranslations: any = {
        'es': {
          'Home': 'Inicio',
          'Profile': 'Perfil',
          'Messages': 'Mensajes',
          'Settings': 'Configuración',
          'Get Verified': 'Verificarse',
          'Trending': 'Tendencias',
          'Explore': 'Explorar',
          'Bookmarks': 'Marcadores',
          'Games': 'Juegos',
          'Staking': 'Apuesta',
          'Launch Your Token': 'Lanza Tu Token',
          'Sign Out': 'Cerrar Sesión',
          'Members': 'Miembros',
          'Following': 'Siguiendo',
          'Followers': 'Seguidores',
          'Posts': 'Publicaciones',
          'Edit Profile': 'Editar Perfil',
          'Delete Account': 'Eliminar Cuenta',
          'Search @handle or posts...': 'Buscar @usuario o publicaciones...',
          'Trenches': 'Trincheras',
          'followers': 'seguidores',
          'following': 'siguiendo',
          'Like': 'Me gusta',
          'Reply': 'Responder',
          'Share': 'Compartir',
          'View all trending': 'Ver todas las tendencias',
          'Game': 'Juego',
          'TRENDING': 'TENDENCIAS',
          'Follow': 'Seguir',
          'Unfollow': 'Dejar de seguir',
          'Block': 'Bloquear',
          'Report': 'Reportar',
          'Not Interested': 'No me interesa',
          'Analytics': 'Analíticas',
          'Wallet': 'Billetera',
          'Video': 'Video',
          'Rewards': 'Recompensas',
          'Create': 'Crear',
          'launch': 'lanzar',
          'token': 'token',
          'ready': 'listo',
          'Soon': 'Pronto',
          'Coming': 'Próximamente',
          'Get': 'Obtener',
          'own': 'propio',
          'cryptocurrency': 'criptomoneda',
          'zero': 'cero',
          'coding': 'codificación',
          'required': 'requerido',
          'deploy': 'desplegar',
          'manage': 'gestionar',
          'blockchain': 'blockchain',
          'powerful': 'poderoso',
          'the': 'el',
          'be': 'ser',
          'to': 'a',
          'of': 'de',
          'and': 'y',
          'a': 'un',
          'in': 'en',
          'that': 'que',
          'have': 'tener',
          'I': 'yo',
          'it': 'eso',
          'for': 'para',
          'not': 'no',
          'on': 'en',
          'with': 'con',
          'he': 'él',
          'as': 'como',
          'you': 'tú',
          'do': 'hacer',
          'at': 'en',
          'this': 'esto',
          'but': 'pero',
          'his': 'su',
          'by': 'por',
          'from': 'de',
          'they': 'ellos',
          'she': 'ella',
          'or': 'o',
          'an': 'un',
          'will': 'será',
          'my': 'mi',
          'one': 'uno',
          'all': 'todo',
          'would': 'haría',
          'there': 'ahí',
          'their': 'su',
          'what': 'qué',
          'so': 'entonces',
          'up': 'arriba',
          'out': 'fuera',
          'if': 'si',
          'about': 'acerca',
          'who': 'quien',
          'which': 'cual',
          'go': 'ir',
          'me': 'me',
          'when': 'cuando',
          'make': 'hacer',
          'can': 'poder',
          'time': 'tiempo',
          'just': 'solo',
          'him': 'él',
          'know': 'saber',
          'take': 'tomar',
          'people': 'gente',
          'into': 'en',
          'year': 'año',
          'your': 'tu',
          'good': 'bueno',
          'some': 'alguno',
          'could': 'podría',
          'them': 'ellos',
          'see': 'ver',
          'other': 'otro',
          'than': 'que',
          'then': 'entonces',
          'now': 'ahora',
          'look': 'mirar',
          'only': 'solo',
          'come': 'venir',
          'over': 'sobre',
          'think': 'pensar',
          'also': 'también',
          'work': 'trabajo',
          'life': 'vida',
          'new': 'nuevo',
          'way': 'camino',
          'may': 'puede',
          'say': 'decir',
          'each': 'cada',
          'day': 'día',
          'use': 'usar',
          'her': 'ella',
          'how': 'como',
          'our': 'nuestro',
          'man': 'hombre',
          'many': 'muchos',
          'where': 'donde',
          'much': 'mucho',
          'find': 'encontrar',
          'here': 'aquí',
          'thing': 'cosa',
          'give': 'dar',
          'well': 'bien',
        },
        'fr': {
          'Home': 'Accueil',
          'Profile': 'Profil',
          'Messages': 'Messages',
          'Settings': 'Paramètres',
          'Get Verified': 'Être Vérifié',
          'Trending': 'Tendances',
          'Explore': 'Explorer',
          'Bookmarks': 'Signets',
          'Games': 'Jeux',
          'Staking': 'Jalonnement',
          'Launch Your Token': 'Lancez Votre Jeton',
          'Sign Out': 'Déconnexion',
          'Members': 'Membres',
          'Following': 'Abonnements',
          'Followers': 'Abonnés',
          'Posts': 'Publications',
          'Edit Profile': 'Modifier le Profil',
          'Delete Account': 'Supprimer le Compte',
          'Search @handle or posts...': 'Rechercher @pseudo ou publications...',
          'Trenches': 'Tranchées',
          'followers': 'abonnés',
          'following': 'abonnements',
          'Like': 'J\'aime',
          'Reply': 'Répondre',
          'Share': 'Partager',
          'View all trending': 'Voir toutes les tendances',
          'Game': 'Jeu',
          'TRENDING': 'TENDANCES',
          'Follow': 'Suivre',
          'Unfollow': 'Ne plus suivre',
          'Block': 'Bloquer',
          'Report': 'Signaler',
          'Not Interested': 'Pas intéressé',
          'Analytics': 'Analytiques',
          'Wallet': 'Portefeuille',
          'Video': 'Vidéo',
          'Rewards': 'Récompenses',
          'Create': 'Créer',
          'launch': 'lancer',
          'token': 'jeton',
          'ready': 'prêt',
          'Soon': 'Bientôt',
          'Coming': 'À venir',
          'Get': 'Obtenir',
          'own': 'propre',
          'cryptocurrency': 'cryptomonnaie',
          'zero': 'zéro',
          'coding': 'codage',
          'required': 'requis',
          'deploy': 'déployer',
          'manage': 'gérer',
          'blockchain': 'blockchain',
          'powerful': 'puissant',
          'the': 'le',
          'be': 'être',
          'to': 'à',
          'of': 'de',
          'and': 'et',
          'a': 'un',
          'in': 'dans',
          'that': 'que',
          'have': 'avoir',
          'I': 'je',
          'it': 'il',
          'for': 'pour',
          'not': 'pas',
          'on': 'sur',
          'with': 'avec',
          'he': 'il',
          'as': 'comme',
          'you': 'vous',
          'do': 'faire',
          'at': 'à',
          'this': 'ce',
          'but': 'mais',
          'his': 'son',
          'by': 'par',
          'from': 'de',
          'they': 'ils',
          'she': 'elle',
          'or': 'ou',
          'an': 'un',
          'will': 'sera',
          'my': 'mon',
          'one': 'un',
          'all': 'tout',
          'would': 'ferait',
          'there': 'là',
          'their': 'leur',
          'what': 'quoi',
          'so': 'alors',
          'up': 'haut',
          'out': 'dehors',
          'if': 'si',
          'about': 'environ',
          'who': 'qui',
          'which': 'lequel',
          'go': 'aller',
          'me': 'moi',
          'when': 'quand',
          'make': 'faire',
          'can': 'peut',
          'time': 'temps',
          'just': 'juste',
          'him': 'lui',
          'know': 'savoir',
          'take': 'prendre',
          'people': 'gens',
          'into': 'dans',
          'year': 'année',
          'your': 'votre',
          'good': 'bon',
          'some': 'quelque',
          'could': 'pourrait',
          'them': 'eux',
          'see': 'voir',
          'other': 'autre',
          'than': 'que',
          'then': 'alors',
          'now': 'maintenant',
          'look': 'regarder',
          'only': 'seulement',
          'come': 'venir',
          'over': 'sur',
          'think': 'penser',
          'also': 'aussi',
          'work': 'travail',
          'life': 'vie',
          'new': 'nouveau',
          'way': 'chemin',
          'may': 'peut',
          'say': 'dire',
          'each': 'chaque',
          'day': 'jour',
          'use': 'utiliser',
          'her': 'elle',
          'how': 'comment',
          'our': 'notre',
          'man': 'homme',
          'many': 'beaucoup',
          'where': 'où',
          'much': 'beaucoup',
          'find': 'trouver',
          'here': 'ici',
          'thing': 'chose',
          'give': 'donner',
          'well': 'bien',
        },
        'zh': {
          'Home': '主页',
          'Profile': '个人资料',
          'Messages': '消息',
          'Settings': '设置',
          'Get Verified': '获得验证',
          'Trending': '趋势',
          'Explore': '探索',
          'Bookmarks': '书签',
          'Games': '游戏',
          'Staking': '质押',
          'Launch Your Token': '启动您的代币',
          'Sign Out': '登出',
          'Members': '成员',
          'Following': '关注',
          'Followers': '粉丝',
          'Posts': '帖子',
          'Edit Profile': '编辑资料',
          'Delete Account': '删除账户',
          'Analytics': '分析',
          'Wallet': '钱包',
          'Video': '视频',
          'Rewards': '奖励',
          'Create': '创建',
          'launch': '启动',
          'token': '代币',
          'ready': '准备好',
          'Soon': '即将推出',
          'Coming': '即将到来',
          'Get': '获得',
          'own': '自己的',
          'cryptocurrency': '加密货币',
          'zero': '零',
          'coding': '编码',
          'required': '需要',
          'deploy': '部署',
          'manage': '管理',
          'blockchain': '区块链',
          'powerful': '强大的',
          'the': '这个',
          'be': '是',
          'to': '到',
          'of': '的',
          'and': '和',
          'a': '一个',
          'in': '在',
          'that': '那个',
          'have': '有',
          'I': '我',
          'it': '它',
          'for': '为了',
          'not': '不',
          'on': '在',
          'with': '与',
          'he': '他',
          'as': '作为',
          'you': '你',
          'do': '做',
          'at': '在',
          'this': '这个',
          'but': '但是',
          'his': '他的',
          'by': '通过',
          'from': '从',
          'they': '他们',
          'she': '她',
          'or': '或者',
          'an': '一个',
          'will': '将',
          'my': '我的',
          'one': '一个',
          'all': '所有',
          'would': '会',
          'there': '那里',
          'their': '他们的',
          'what': '什么',
          'so': '所以',
          'up': '向上',
          'out': '出去',
          'if': '如果',
          'about': '关于',
          'who': '谁',
          'which': '哪个',
          'go': '去',
          'me': '我',
          'when': '当',
          'make': '制作',
          'can': '可以',
          'time': '时间',
          'just': '只是',
          'him': '他',
          'know': '知道',
          'take': '拿',
          'people': '人们',
          'into': '进入',
          'year': '年',
          'your': '你的',
          'good': '好',
          'some': '一些',
          'could': '可以',
          'them': '他们',
          'see': '看',
          'other': '其他',
          'than': '比',
          'then': '然后',
          'now': '现在',
          'look': '看',
          'only': '只有',
          'come': '来',
          'over': '结束',
          'think': '想',
          'also': '也',
          'work': '工作',
          'life': '生活',
          'new': '新的',
          'way': '方式',
          'may': '可能',
          'say': '说',
          'each': '每个',
          'day': '天',
          'use': '使用',
          'her': '她的',
          'how': '如何',
          'our': '我们的',
          'man': '男人',
          'many': '许多',
          'where': '哪里',
          'much': '很多',
          'find': '找到',
          'here': '这里',
          'thing': '事情',
          'give': '给',
          'well': '好',
        }
      };

      const langTranslations = basicTranslations[targetLang];
      if (langTranslations && langTranslations[text]) {
        return langTranslations[text];
      }

      // Return original text if no translation available
      return text;
    });

    return res.status(200).json({
      success: true,
      translations
    });

  } catch (error) {
    console.error('Translation API error:', error);
    return res.status(500).json({
      error: 'Translation failed',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
}